meta_product_name: "Pick and watch"
meta_title: "Pickandwatch - The best social media app to find easily a good movie to see"
meta_description: "Share movies liked with your friends and find easily ideas of good movies to watch"
meta_image: "metapicture.png" # should exist in `app/assets/images/`

